spring.application.name=PetPal
spring.datasource.url=jdbc:postgresql://ep-red-shape-a8xzds2i-pooler.eastus2.azure.neon.tech/neondb?user=neondb_owner&password=npg_w6E5mxZiQtJO&sslmode=require&channelBinding=require
spring.jpa.hibernate.ddl-auto=update

#Log out sql queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE