spring.application.name=PetPal
spring.datasource.url=${DATABASE_URL}

#Log out sql queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.level.org.springframework.web=DEBUG